import {describe,it,expect} from 'vitest';
import {fetchGithubSbom} from '../src/sbom-runtime.js';
const api='https://api.github.com/repos/example/demo/dependency-graph/sbom';
const poll=api+'/fetch-report/4bab1a7e-da63-4828-9488-44e0e01a7c1b';
const ready='https://downloads.example.test/report.json?signature=fixture';
const sbom={SPDXID:'SPDXRef-DOCUMENT',spdxVersion:'SPDX-2.3',name:'example/demo',packages:[]};
const headers={'X-GitHub-Api-Version':'2026-03-10',authorization:'Bearer fixture-token'};
const config={approvedDownloadHosts:['downloads.example.test'],pollIntervalMs:1,maxPolls:3,timeoutMs:500};
function mock(responses:Response[]) {const calls:{url:string;options:RequestInit}[]=[];return {calls,fetcher:async(url:string,options:RequestInit)=>{calls.push({url,options});const response=responses.shift();if(!response)throw new Error('fixture exhausted');return response;}};}
const generated=()=>new Response(JSON.stringify({sbom_url:poll}),{status:201});
const done=()=>new Response(null,{status:302,headers:{location:ready}});
describe('SBOM async flow (mock transport only)',()=>{
 it('generates, polls pending, then downloads SPDX without forwarding auth',async()=>{const m=mock([generated(),new Response(null,{status:202}),done(),new Response(JSON.stringify(sbom))]);expect(await fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).toEqual(sbom);expect(m.calls.map(c=>c.url)).toEqual([api+'/generate-report',poll,poll,ready]);expect(m.calls[0].options.headers).toMatchObject({authorization:'Bearer fixture-token'});expect(m.calls[3].options.headers).not.toHaveProperty('authorization');expect(m.calls.every(c=>c.options.redirect==='manual'&&c.options.credentials==='omit')).toBe(true);});
 it('bounds pending retries',async()=>{const m=mock([generated(),new Response(null,{status:202}),new Response(null,{status:202}),new Response(null,{status:202})]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow('poll limit');expect(m.calls).toHaveLength(4);});
 it('times out a hanging transport',async()=>{await expect(fetchGithubSbom('example','demo',headers,{...config,timeoutMs:20,fetcher:async()=>new Promise(()=>{})})).rejects.toThrow('deadline');});
 it('rejects non-created generation and malformed generation payload',async()=>{for(const response of [new Response('{}',{status:403}),new Response('{}',{status:200}),new Response('bad',{status:201}),new Response('{}',{status:201})]){const m=mock([response]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow();expect(m.calls).toHaveLength(1);}});
 it('rejects foreign/private polling URLs before requesting them',async()=>{for(const url of ['http://127.0.0.1/report','https://api.github.com/repos/other/repo/dependency-graph/sbom/fetch-report/4bab1a7e-da63-4828-9488-44e0e01a7c1b']){const m=mock([new Response(JSON.stringify({sbom_url:url}),{status:201})]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow();expect(m.calls).toHaveLength(1);}});
 it('rejects unapproved/credential/private download URLs',async()=>{for(const url of ['http://127.0.0.1/a','https://user:secret@downloads.example.test/a','https://evil.example.test/a','https://169.254.169.254/a']){const m=mock([generated(),new Response(null,{status:302,headers:{location:url}})]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow();expect(m.calls).toHaveLength(2);}});
 it('rejects unexpected polling and download redirects',async()=>{for(const responses of [[generated(),new Response('{}',{status:404})],[generated(),done(),new Response(null,{status:302,headers:{location:'https://evil.example.test'}})]]){const m=mock(responses);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow();}});
 it('rejects invalid SPDX and oversized bodies',async()=>{for(const response of [new Response('{}'),new Response('x',{headers:{'content-length':'20000000'}})]){const m=mock([generated(),done(),response]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow();}});
 it('requires a reviewed host and matching explicit API version',async()=>{const m=mock([]);await expect(fetchGithubSbom('example','demo',headers,{...config,approvedDownloadHosts:[],fetcher:m.fetcher})).rejects.toThrow();await expect(fetchGithubSbom('example','demo',{'X-GitHub-Api-Version':'2022-11-28'},{...config,fetcher:m.fetcher})).rejects.toThrow('version');expect(m.calls).toHaveLength(0);});
});
describe('SBOM additional bounds',()=>{
 it('aborts an outstanding poll sleep at the whole-flow deadline',async()=>{const m=mock([generated(),new Response(null,{status:202})]);const start=Date.now();await expect(fetchGithubSbom('example','demo',headers,{...config,pollIntervalMs:60000,timeoutMs:25,fetcher:m.fetcher})).rejects.toThrow('deadline');expect(Date.now()-start).toBeLessThan(500);});
 it('enforces streaming size without trusting content length',async()=>{const oversized=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new Uint8Array(15*1024*1024+1));controller.close();}});const m=mock([generated(),done(),new Response(oversized)]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow('limit');});
 it('rejects unsafe headers and request bounds without network',async()=>{for(const bad of [{...config,maxPolls:0},{...config,timeoutMs:Infinity},{...config,pollIntervalMs:-1},{...config,approvedDownloadHosts:['localhost']}]){const m=mock([]);await expect(fetchGithubSbom('example','demo',headers,{...bad,fetcher:m.fetcher})).rejects.toThrow();expect(m.calls).toHaveLength(0);}const m=mock([]);await expect(fetchGithubSbom('example','demo',{...headers,cookie:'fixture'},{...config,fetcher:m.fetcher})).rejects.toThrow('headers');});
 it('does not expose transport error details',async()=>{await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:async()=>{throw new Error('Bearer secret');}})).rejects.toThrow('SBOM transport failed');});
});
describe('live-discovered body errors',()=>{
 it('reports a whole-flow deadline for a stalled response body',async()=>{const stalled=new ReadableStream<Uint8Array>({start(){}});const m=mock([generated(),done(),new Response(stalled)]);await expect(fetchGithubSbom('example','demo',headers,{...config,timeoutMs:25,fetcher:m.fetcher})).rejects.toThrow('deadline');});
 it('sanitizes response-body transport errors',async()=>{const broken=new ReadableStream<Uint8Array>({start(controller){controller.error(new Error('fixture-secret'));}});const m=mock([generated(),done(),new Response(broken)]);await expect(fetchGithubSbom('example','demo',headers,{...config,fetcher:m.fetcher})).rejects.toThrow('SBOM body read failed');});
});
