import {describe,it,expect} from 'vitest';
import {applyPatch} from 'diff';
import {proposeSbom,SBOM_DEMO_SOURCE} from '../src/sbom-proposal.js';
describe('bounded SBOM proposal',()=>{
 it('emits a separate patch and preserves headers and source evidence',()=>{const p=proposeSbom(SBOM_DEMO_SOURCE,'consumer.ts','export const helper = true;',['downloads.example.test']);expect(p.status).toBe('proposed');if(p.status!=='proposed')throw new Error(p.reason);expect(p.validation).toBe('not_run');expect(p.preview).toContain('autoshimGithubSbom');expect(p.preview).toContain('Bearer ${token}');expect(p.patch).toContain('/dev/null');expect(p.sourceSha256).toHaveLength(64);expect(applyPatch(SBOM_DEMO_SOURCE,p.consumerPatch)).toBe(p.preview);});
 it('rejects unsupported versions, dynamic URLs, response shapes and side effects',()=>{for(const source of [SBOM_DEMO_SOURCE.replace('2026-03-10','2022-11-28'),SBOM_DEMO_SOURCE.replace('"https://api.github.com/repos/example/demo/dependency-graph/sbom"','url'),SBOM_DEMO_SOURCE.replace('.sbom;',';'),SBOM_DEMO_SOURCE.replace('return (','console.log(response); return (')])expect(proposeSbom(source,'consumer.ts','helper',['downloads.example.test']).status).toBe('unavailable');});
 it('rejects fetch shadows, helper collisions, missing host approval and unsafe filenames',()=>{for(const [source,file,hosts] of [[`const fetch=custom;\n${SBOM_DEMO_SOURCE}`,'consumer.ts',['downloads.example.test']],[`const autoshimGithubSbom=1;\n${SBOM_DEMO_SOURCE}`,'consumer.ts',['downloads.example.test']],[SBOM_DEMO_SOURCE,'../consumer.ts',['downloads.example.test']],[SBOM_DEMO_SOURCE,'consumer.ts',[]]] as const)expect(proposeSbom(source,file,'helper',hosts).status).toBe('unavailable');});
 it('rejects SDK calls, complex functions and malformed source',()=>{for(const source of ['export const result=await octokit.request("GET /repos/{owner}/{repo}/dependency-graph/sbom");',SBOM_DEMO_SOURCE.replace('const response','const other=1; const response'),SBOM_DEMO_SOURCE+'\n{'])expect(proposeSbom(source,'consumer.ts','helper',['downloads.example.test']).status).toBe('unavailable');});
});
