import {describe,it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createSbomProposal,runSbomDemo} from '../src/proposal.js';
import {SBOM_DEMO_SOURCE} from '@autoshim/core';
describe('proposal output and owned demo',()=>{
 it('writes a separate preview and leaves source unchanged; refuses overwrite',async()=>{const dir=await mkdtemp(join(tmpdir(),'sbom-proposal-'));try{const repo=join(dir,'repo');await mkdir(repo);await writeFile(join(repo,'consumer.ts'),SBOM_DEMO_SOURCE);const out=join(dir,'out');const result=await createSbomProposal({repo,file:'consumer.ts',out,downloadHost:['downloads.example.test']});expect(result.status).toBe('proposed');expect(await readFile(join(repo,'consumer.ts'),'utf8')).toBe(SBOM_DEMO_SOURCE);expect(await readFile(join(out,'proposal.patch'),'utf8')).toContain('/generate-report');await expect(createSbomProposal({repo,file:'consumer.ts',out,downloadHost:['downloads.example.test']})).rejects.toThrow();}finally{await rm(dir,{recursive:true,force:true});}});
 it('refuses helper collisions, symlinks, traversal and outputs inside consumer',async()=>{const dir=await mkdtemp(join(tmpdir(),'sbom-refuse-'));try{const repo=join(dir,'repo');await mkdir(repo);await writeFile(join(repo,'consumer.ts'),SBOM_DEMO_SOURCE);await symlink(join(repo,'consumer.ts'),join(repo,'linked.ts'));for(const file of ['../consumer.ts','linked.ts'])await expect(createSbomProposal({repo,file,out:join(dir,'out'),downloadHost:['downloads.example.test']})).rejects.toThrow();await expect(createSbomProposal({repo,file:'consumer.ts',out:join(repo,'out'),downloadHost:['downloads.example.test']})).rejects.toThrow();await writeFile(join(repo,'autoshim-sbom.ts'),'existing');await expect(createSbomProposal({repo,file:'consumer.ts',out:join(dir,'out'),downloadHost:['downloads.example.test']})).rejects.toThrow('helper');}finally{await rm(dir,{recursive:true,force:true});}});
 it('executes only owned demo with mock evidence',async()=>{const dir=await mkdtemp(join(tmpdir(),'sbom-demo-'));try{const result=await runSbomDemo(join(dir,'out'));expect(result.status).toBe('mock_validated');expect(result.exitCode).toBe(0);const evidence=JSON.parse(await readFile(join(dir,'out','validation.json'),'utf8'));expect(evidence.status).toBe('mock_validated');expect(evidence.stdout).toContain('# pass 4');}finally{await rm(dir,{recursive:true,force:true});}});
});
